### ISSUE TITLE
Can't locate loadable object for module nginx

### ISSUE THREAD

**Issue by mwlczk** [weiss/ngx_http_upload#3]
Hello @weiss and happy Easter,
my set-up is as follows:

- nginx version: 1.14.2
- perl version: perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi
- runtime environment: official nginx:alpine docker (image id 0be75340bd9b) (most likely we don't need that info).
- i have downloaded your upload.pm and modified the secret and the uri_prefix_components (=1)
- I have "load_module /usr/lib/nginx/modules/ngx_http_perl_module.so;"
- have the special "location / {}
- have the settings in ejabberd.yml 

the nginx is still starting until this point. 

But if I uncomment:
```
    # perl_modules /usr/local/lib/perl; # Path to upload.pm.
    # perl_require upload.pm;
```
in the "http {}" part of nginx and then reload the configuration, nginx produces immediately the following error:
```
Can't locate nginx.pm in @INC (you may need to install the nginx module) (@INC contains: /usr/local/lib/perl /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl).
BEGIN failed--compilation aborted.
2019/04/19 14:16:40 [alert] 17#17: perl_parse() failed: 2
nginx: [alert] perl_parse() failed: 2
```
I found nginx.pm in **/usr/lib/perl5/vendor_perl/x86_64-linux-thread-multi** and copied it down one folder to **/usr/lib/perl5/vendor_perl**.
After this "copying" I encountered the following slightly different error:
```
Can't locate loadable object for module nginx in @INC (@INC contains: /usr/local/lib/perl /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at -e line 0.
Compilation failed in require.
BEGIN failed--compilation aborted.
2019/04/19 14:24:05 [alert] 37#37: perl_parse() failed: 255
nginx: [alert] perl_parse() failed: 255
```

might it be due to incompatible perl-versions?

**Comment by weiss** [comment]
> `Can't locate nginx.pm in @INC`

Does it help if you add the following `perl_modules` line (in addition to the existing `perl_modules` line)?

```nginx
perl_modules /usr/lib/perl5/vendor_perl/x86_64-linux-thread-multi
```

> `Can't locate loadable object for module nginx in @INC`

At that point it fails to load the `nginx.so` required by `nginx.pm`, I think.

**Comment by licaon-kter** [comment]
Works fine here with 5.28, this sounds like a deps installation issue.

**Comment by mwlczk** [comment]
> > `Can't locate nginx.pm in @INC`
> 
> Does it help if you add the following `perl_modules` line (in addition to the existing `perl_modules` line)?
> 
> ```nginx
> perl_modules /usr/lib/perl5/vendor_perl/x86_64-linux-thread-multi
> ```

cannot use two `perl_modules` statements in nginx.conf. Would have been to easy. :(

I guess as @licaon-kter says it is something with the nginx:alpine image, where i installed the ngx_perl_module on top. Gonna ask in their repository.

**Comment by mwlczk** [comment]
meanwhile I was able to get one step further using another official image "nginx:alpine-perl".
but still something with dependencies is not correct
`nginx: [alert] version 1.14.2 of nginx.pm is required, but 1.15.12 was found
` 
this is a thing for the other repo. thx guys

**Comment by weiss** [comment]
> cannot use two `perl_modules` statements in nginx.conf.

Hmm, I do this myself, and it works for me.

**Comment by mwlczk** [comment]
thanks to the hint of the [nginx](https://github.com/nginxinc/docker-nginx/issues/325) guys, i was able to setup this correctly.

basically, they are building their own nginx from source into the "image". this build does not have anything to do with the nginx-build from the official alpine-repos. thus installing any module/addon from alpine repos breaks the nginx (sometimes).

solution is to use the "nginx:alpine-perl" image. this has "streams" enabled/loaded and the perl module can be loaded via the nginx.conf. no need to install any other packages.
