### ISSUE TITLE
Undefined subroutine &upload::handle

### ISSUE THREAD

**Issue by Mr5quid** [weiss/ngx_http_upload#6]
Hi!
My current setup:
- Device : Odroid XU4 (ARMv7 32 bits)
- System : Armbian 5.85 Stable Debian Stretch 9
- Linux : 4.14.111-odroidxu4
- nginx : 1.10.3
- perl : 5.24.1
- libnginx-mod-http-perl : 1.10.3
- Prosody : 0.11.2

Whenever I try to upload a file using this module, nginx throws me back the following error:

`[error] 2118#2118: *1 call_sv("upload::handle") failed: "Undefined subroutine &upload::handle called.", client: XXX.XXX.XXX.XXX, server: share.example.com, request: "PUT /825223ad-62d6-470c-a23e-0e05493e0851/RGLF37mWRJ26UfeKQkTX4A.jpg?v=3640efdbe186ffdd90dd639fb45a1dbd9d2708ed21d4bb646d0e8159cf022a10 HTTP/1.1", host: "share.example.com"`

From what I gathered, this is in fact a Perl error. I tried to look into it myself but unfortunately I really know nothing about Perl. Any thoughts on what could cause this?

**Comment by weiss** [comment]
This means Nginx can't find (or call) `upload.pm` for some reason.

**Comment by Mr5quid** [comment]
Yes indeed, turns out I just had to put the instructions
`perl_modules /usr/local/lib/perl;`
`perl_require upload.pm;`
BEFORE
`include /etc/nginx/sites-available/*;`
in the global nginx config within the `http` block.

Sorry for the trouble, but thanks for the help as well as for the module.
